### ISSUE TITLE
Aimbot PitchPattern False Flag

### ISSUE THREAD

**Issue by notperry1234567890** [herobrine99dan/NESS-Reloaded#29] opened 2020-06-08 12:45 UTC
if you have optifine just hold the zoom button down so you zoom and just look up and down and just look around and you will start to false that a ton

**Comment by herobrine99dan** [comment] 2020-06-08 12:51
Can you do a video or send some screenshots?

**Comment by A248** [comment] 2020-06-23 22:23
I can confirm this false positive

**Comment by herobrine99dan** [comment] 2020-06-24 09:52
I don't know how to fix It...

**Comment by herobrine99dan** [comment] 2020-08-20 09:40
Maybe after a month i have a fix to this problem!

**Comment by herobrine99dan** [comment] 2020-09-20 19:13
Okay the new Aimbot GCD (before it was called PitchPattern) is better than before, it should give low false flag probability with optifine.
Anyway i will not close this for now, since Aimbot GCD needs more tests.

**Comment by herobrine99dan** [comment] 2021-01-22 15:26
Fixed with https://github.com/herobrine99dan/NESS-Reloaded/commit/c3573c26aa16f4f7dd40ac664d947d1075cfe95e

**Closed by herobrine99dan** 2021-01-22 15:26 UTC
Labels: false positive
